import type { ComponentMeta, PropMeta, SkillFormat, SkillsConfig } from '../util/messaging';
import { generateExampleJSX, generateImport, splitComponentId } from './codegen';

export type { SkillFormat };

export interface SkillArtifact {
  relativePath: string;
  contents: string;
}

/** A generated skill file that exists on disk for a single component. */
export interface ComponentSkillFile {
  path: string;
  label: string;
  format: SkillFormat;
}

/** User guidance resolved into plain markdown blocks, ready to inject. */
export interface ResolvedGuidance {
  /** Component id (pkg#Name) -> free-text guidance markdown (may be empty). */
  perComponent: Record<string, string>;
}

type GuidanceConfig = Pick<SkillsConfig, 'instructions'>;

/**
 * Resolves the per-component free-text notes into a guidance block per component id.
 * Pure and deterministic so regeneration always reproduces the same output.
 */
export function resolveGuidance(cfg: GuidanceConfig, componentIds: string[]): ResolvedGuidance {
  const perComponent: Record<string, string> = {};
  for (const id of componentIds) {
    const free = cfg.instructions?.[id]?.trim();
    if (free) perComponent[id] = free;
  }
  return { perComponent };
}

const AUTOGEN_HEADER =
  '<!-- AUTO-GENERATED by Snapds. Do not hand-edit; regenerate via "Snapds: Generate Skills". -->';

export function kebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-+|-+$/g, '');
}

function componentDescription(meta: ComponentMeta): string {
  if (meta.description?.trim()) return meta.description.trim();
  const { pkg, name } = splitComponentId(meta.id);
  return `Public props contract and usage for the ${name} component${pkg ? ` from ${pkg}` : ''}.`;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Resolves a unique kebab-case slug per component, deduping collisions with -2, -3, … */
function resolveSlugs(components: ComponentMeta[]): Map<string, string> {
  const used = new Set<string>();
  const map = new Map<string, string>();
  for (const meta of components) {
    const { name } = splitComponentId(meta.id);
    const base = kebab(name) || 'component';
    let candidate = base;
    let n = 2;
    while (used.has(candidate)) candidate = `${base}-${n++}`;
    used.add(candidate);
    map.set(meta.id, candidate);
  }
  return map;
}

/**
 * Returns the destination-relative skill file paths snapds would write for the
 * component `id`. `components` MUST be the full set so the deduped slug matches
 * exactly what `buildArtifacts` emits.
 */
export function expectedSkillRelPaths(
  components: ComponentMeta[],
  id: string,
): { augment: string; generic: string } {
  // biome-ignore lint/style/noNonNullAssertion: id comes from the same components array used to build the slug map
  const slug = resolveSlugs(components).get(id)!;
  return {
    augment: `.augment/skills/snapds-${slug}/SKILL.md`,
    generic: `snapds-skills/${slug}.md`,
  };
}

function propsTable(props: PropMeta[]): string {
  if (!props.length) return 'No public props.';
  const header =
    '| Prop | Type | Required | Default | Values | Description |\n' +
    '|------|------|----------|---------|--------|-------------|';
  const rows = props.map((p) => {
    const type = escapeCell(p.type);
    const required = p.required ? 'yes' : 'no';
    const def = p.defaultValue !== undefined ? escapeCell(JSON.stringify(p.defaultValue)) : '—';
    const values = p.enumValues?.length ? p.enumValues.map(escapeCell).join(' \\| ') : '—';
    const desc = p.description ? escapeCell(p.description) : '';
    return `| ${escapeCell(p.name)} | ${type} | ${required} | ${def} | ${values} | ${desc} |`;
  });
  return [header, ...rows].join('\n');
}

export function buildComponentSkillMarkdown(
  meta: ComponentMeta,
  format: SkillFormat,
  guidance = '',
): string {
  const { pkg, name } = splitComponentId(meta.id);
  const desc = componentDescription(meta);
  const importLine = generateImport(meta);
  const example = generateExampleJSX(meta);
  const table = propsTable(meta.props);

  const parts: string[] = [];
  if (format === 'augment') {
    parts.push(
      '---',
      `name: snapds-${kebab(name)}`,
      `description: How to use ${name}${pkg ? ` from ${pkg}` : ''}. Use when adding or modifying ${name} in JSX/TSX.`,
      '---',
    );
  }
  parts.push(AUTOGEN_HEADER, '', `# ${name}`, '', desc, '');

  if (format === 'augment') {
    parts.push('## Import', '', '```ts', importLine, '```', '');
    parts.push('## Usage', '', '```tsx', example, '```', '');
    parts.push('## Props', '', table, '');
  } else {
    parts.push('**Import**', '', '```ts', importLine, '```', '');
    parts.push('**Usage**', '', '```tsx', example, '```', '');
    parts.push(table, '');
  }
  if (guidance.trim()) {
    parts.push(format === 'augment' ? '## Additional guidance' : '**Additional guidance**', '');
    parts.push(guidance.trim(), '');
  }
  return parts.join('\n');
}

export function buildMainSkillMarkdown(
  components: ComponentMeta[],
  format: SkillFormat,
  slugs: Map<string, string>,
): string {
  const pkgs = Array.from(
    new Set(components.map((c) => splitComponentId(c.id).pkg).filter(Boolean)),
  );

  const parts: string[] = [];
  if (format === 'augment') {
    parts.push(
      '---',
      'name: snapds',
      'description: Index/router for the Snapds design system; load a component sub-skill on demand.',
      '---',
    );
  }
  parts.push(AUTOGEN_HEADER, '', '# Snapds Design System', '');
  parts.push('## Conventions', '');
  parts.push(
    `- Import components from their package${pkgs.length ? ` (${pkgs.join(', ')})` : ''}; see each component's Import section.`,
    '- Prefer these components over raw HTML equivalents.',
    '- Always supply required props; optional props fall back to documented defaults.',
    "- Open a component's detail file only when you actually use that component.",
    '',
  );
  parts.push('## Components', '');

  const byPkg = new Map<string, ComponentMeta[]>();
  for (const c of components) {
    const key = splitComponentId(c.id).pkg || '(local)';
    // biome-ignore lint/style/noNonNullAssertion: Map.set() is called immediately before .get(), so the key is guaranteed to exist
    (byPkg.get(key) ?? byPkg.set(key, []).get(key)!).push(c);
  }

  for (const [pkg, comps] of byPkg) {
    parts.push(`### ${pkg}`, '');
    if (format === 'augment') {
      parts.push('| Component | Skill |', '|-----------|-------|');
      for (const c of comps) {
        // biome-ignore lint/style/noNonNullAssertion: comps derives from components, the same array used to build slugs
        const slug = slugs.get(c.id)!;
        parts.push(
          `| ${splitComponentId(c.id).name} | [snapds-${slug}](../snapds-${slug}/SKILL.md) |`,
        );
      }
    } else {
      parts.push('| Component | Detail file |', '|-----------|-------------|');
      for (const c of comps) {
        // biome-ignore lint/style/noNonNullAssertion: comps derives from components, the same array used to build slugs
        const slug = slugs.get(c.id)!;
        parts.push(
          `| ${splitComponentId(c.id).name} | [./snapds-skills/${slug}.md](./snapds-skills/${slug}.md) |`,
        );
      }
    }
    parts.push('');
  }
  return parts.join('\n');
}

export function buildAugmentSkillArtifacts(
  components: ComponentMeta[],
  changedIds?: Set<string>,
  guidance?: ResolvedGuidance,
): SkillArtifact[] {
  const slugs = resolveSlugs(components);
  // The index always reflects the full component set so routing stays correct.
  const artifacts: SkillArtifact[] = [
    {
      relativePath: 'snapds/SKILL.md',
      contents: buildMainSkillMarkdown(components, 'augment', slugs),
    },
  ];
  for (const meta of components) {
    if (changedIds && !changedIds.has(meta.id)) continue;
    artifacts.push({
      // biome-ignore lint/style/noNonNullAssertion: meta is from components, the same array used to build slugs
      relativePath: `snapds-${slugs.get(meta.id)!}/SKILL.md`,
      contents: buildComponentSkillMarkdown(meta, 'augment', guidance?.perComponent[meta.id]),
    });
  }
  return artifacts;
}

export function buildGenericArtifacts(
  components: ComponentMeta[],
  changedIds?: Set<string>,
  guidance?: ResolvedGuidance,
): SkillArtifact[] {
  const slugs = resolveSlugs(components);
  const artifacts: SkillArtifact[] = [
    {
      relativePath: 'AGENTS.md',
      contents: buildMainSkillMarkdown(components, 'generic', slugs),
    },
  ];
  for (const meta of components) {
    if (changedIds && !changedIds.has(meta.id)) continue;
    artifacts.push({
      // biome-ignore lint/style/noNonNullAssertion: meta is from components, the same array used to build slugs
      relativePath: `snapds-skills/${slugs.get(meta.id)!}.md`,
      contents: buildComponentSkillMarkdown(meta, 'generic', guidance?.perComponent[meta.id]),
    });
  }
  return artifacts;
}

/**
 * Builds skill artifacts for `components`. When `changedIds` is provided, only the
 * index plus detail files for those component ids are emitted (incremental mode);
 * otherwise every detail file is emitted (full mode).
 */
export function buildArtifacts(
  components: ComponentMeta[],
  format: SkillFormat,
  changedIds?: Set<string>,
  guidance?: ResolvedGuidance,
): SkillArtifact[] {
  return format === 'augment'
    ? buildAugmentSkillArtifacts(components, changedIds, guidance)
    : buildGenericArtifacts(components, changedIds, guidance);
}
