import * as path from 'node:path';
import type { ComponentMeta, PropMeta, SkillFormat, SkillsConfig } from '../util/messaging';
import { generateExampleJSX, generateImport, splitComponentId } from './codegen';
import { AGENTS } from './skillAgents';

export type { SkillFormat };

export interface SkillArtifact {
  relativePath: string;
  contents: string;
}

/** A generated skill file that exists on disk for a single component. */
export interface ComponentSkillFile {
  path: string;
  label: string;
  format: SkillFormat;
}

/** User guidance resolved into plain markdown blocks, ready to inject. */
export interface ResolvedGuidance {
  /** Component id (pkg#Name) -> free-text guidance markdown (may be empty). */
  perComponent: Record<string, string>;
}

type GuidanceConfig = Pick<SkillsConfig, 'instructions'>;

/**
 * Resolves the per-component free-text notes into a guidance block per component id.
 * Pure and deterministic so regeneration always reproduces the same output.
 */
export function resolveGuidance(cfg: GuidanceConfig, componentIds: string[]): ResolvedGuidance {
  const perComponent: Record<string, string> = {};
  for (const id of componentIds) {
    const free = cfg.instructions?.[id]?.trim();
    if (free) perComponent[id] = free;
  }
  return { perComponent };
}

const AUTOGEN_HEADER =
  '<!-- AUTO-GENERATED by Snapds. Do not hand-edit; regenerate via "Snapds: Generate Skills". -->';

export function kebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-+|-+$/g, '');
}

function componentDescription(meta: ComponentMeta): string {
  if (meta.description?.trim()) return meta.description.trim();
  const { pkg, name } = splitComponentId(meta.id);
  return `Public props contract and usage for the ${name} component${pkg ? ` from ${pkg}` : ''}.`;
}

function escapeCell(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Resolves a unique kebab-case slug per component, deduping collisions with -2, -3, … */
function resolveSlugs(components: ComponentMeta[]): Map<string, string> {
  const used = new Set<string>();
  const map = new Map<string, string>();
  for (const meta of components) {
    const { name } = splitComponentId(meta.id);
    const base = kebab(name) || 'component';
    let candidate = base;
    let n = 2;
    while (used.has(candidate)) candidate = `${base}-${n++}`;
    used.add(candidate);
    map.set(meta.id, candidate);
  }
  return map;
}

/**
 * Returns the destination-root-relative skill file path snapds would write for
 * the component `id` under `format`, or undefined when the agent has no
 * per-component file (consolidated agents). `components` MUST be the full set so
 * the deduped slug matches exactly what `buildArtifacts` emits.
 */
export function expectedSkillRelPath(
  components: ComponentMeta[],
  id: string,
  format: SkillFormat,
): string | undefined {
  const agent = AGENTS[format];
  if (!agent.componentRelPath) return undefined;
  const slug = resolveSlugs(components).get(id);
  if (!slug) return undefined;
  const rel = agent.componentRelPath(slug);
  return agent.baseDir ? path.posix.join(agent.baseDir, rel) : rel;
}

function propsTable(props: PropMeta[]): string {
  if (!props.length) return 'No public props.';
  const header =
    '| Prop | Type | Required | Default | Values | Description |\n' +
    '|------|------|----------|---------|--------|-------------|';
  const rows = props.map((p) => {
    const type = escapeCell(p.type);
    const required = p.required ? 'yes' : 'no';
    const def = p.defaultValue !== undefined ? escapeCell(JSON.stringify(p.defaultValue)) : '—';
    const values = p.enumValues?.length ? p.enumValues.map(escapeCell).join(' \\| ') : '—';
    const desc = p.description ? escapeCell(p.description) : '';
    return `| ${escapeCell(p.name)} | ${type} | ${required} | ${def} | ${values} | ${desc} |`;
  });
  return [header, ...rows].join('\n');
}

/** Groups components by package, preserving first-seen order. */
function groupByPackage(components: ComponentMeta[]): Map<string, ComponentMeta[]> {
  const byPkg = new Map<string, ComponentMeta[]>();
  for (const c of components) {
    const key = splitComponentId(c.id).pkg || '(local)';
    const list = byPkg.get(key);
    if (list) list.push(c);
    else byPkg.set(key, [c]);
  }
  return byPkg;
}

/** Markdown link from the router to a component detail file, computed per agent. */
function routerLink(format: SkillFormat, slug: string): string {
  const agent = AGENTS[format];
  if (!agent.componentRelPath) return slug;
  const from = path.posix.dirname(agent.routerRelPath);
  const target =
    path.posix.relative(from, agent.componentRelPath(slug)) || agent.componentRelPath(slug);
  const href = target.startsWith('.') ? target : `./${target}`;
  return `[snapds-${slug}](${href})`;
}

/** Full per-component detail: heading/bold sections + a complete props table. */
export function buildComponentSkillMarkdown(
  meta: ComponentMeta,
  format: SkillFormat,
  slug: string,
  guidance = '',
): string {
  const agent = AGENTS[format];
  const { pkg, name } = splitComponentId(meta.id);
  const desc = componentDescription(meta);
  const importLine = generateImport(meta);
  const example = generateExampleJSX(meta);
  const table = propsTable(meta.props);
  const heading = agent.layout !== 'generic';

  const parts: string[] = [];
  const fm = agent.componentFrontmatter?.({ name, pkg, slug, description: desc });
  if (fm) parts.push(fm);
  parts.push(AUTOGEN_HEADER, '', `# ${name}`, '', desc, '');

  if (heading) {
    parts.push('## Import', '', '```ts', importLine, '```', '');
    parts.push('## Usage', '', '```tsx', example, '```', '');
    parts.push('## Props', '', table, '');
  } else {
    parts.push('**Import**', '', '```ts', importLine, '```', '');
    parts.push('**Usage**', '', '```tsx', example, '```', '');
    parts.push(table, '');
  }
  if (guidance.trim()) {
    parts.push(heading ? '## Additional guidance' : '**Additional guidance**', '');
    parts.push(guidance.trim(), '');
  }
  return parts.join('\n');
}

/**
 * Catalog entry for consolidated agents: description, import, usage, and — unless
 * `compact` — the full props table. Inlined into the single catalog file so the
 * agent still gets each component's contract (compact drops props to save tokens).
 */
function buildCatalogEntry(meta: ComponentMeta, guidance = '', compact = false): string {
  const { name } = splitComponentId(meta.id);
  const parts = [
    `### ${name}`,
    '',
    componentDescription(meta),
    '',
    '```tsx',
    generateImport(meta),
    '',
    generateExampleJSX(meta),
    '```',
    '',
  ];
  if (!compact) parts.push(propsTable(meta.props), '');
  if (guidance.trim()) parts.push(guidance.trim(), '');
  return parts.join('\n');
}

/**
 * Builds the router/main file. Its shape adapts to the agent's layout so that
 * always-loaded routers (flat-lazy, consolidated) stay token-cheap:
 * - folder/generic: full component table linking to each detail file.
 * - flat-lazy: minimal — names only; details load on demand.
 * - flat-consolidated: the single catalog file (all components inline, with props).
 */
export function buildMainSkillMarkdown(
  components: ComponentMeta[],
  format: SkillFormat,
  slugs: Map<string, string>,
  guidance?: ResolvedGuidance,
  compact = false,
): string {
  const agent = AGENTS[format];
  const pkgs = Array.from(
    new Set(components.map((c) => splitComponentId(c.id).pkg).filter(Boolean)),
  );

  const parts: string[] = [];
  const fm = agent.routerFrontmatter?.();
  if (fm) parts.push(fm);
  parts.push(AUTOGEN_HEADER, '', '# Snapds Design System', '');
  parts.push('## Conventions', '');
  parts.push(
    `- Import each component using the import in its own Import section${pkgs.length ? ` (sources: ${pkgs.join(', ')})` : ''} — npm packages and in-repo path aliases alike.`,
    '- Prefer these components over raw HTML equivalents.',
    '- Always supply required props; optional props fall back to documented defaults.',
  );

  const byPkg = groupByPackage(components);

  if (agent.layout === 'flat-consolidated') {
    parts.push('', '## Components', '');
    for (const c of components) {
      parts.push(buildCatalogEntry(c, guidance?.perComponent[c.id], compact));
    }
    return parts.join('\n');
  }

  if (agent.layout === 'flat-lazy') {
    // Always-on router stays tiny: name-only discovery; details load on demand.
    parts.push(
      '- Component rules live beside this file; load `snapds-<component>` on demand when you use it.',
      '',
      '## Components',
      '',
    );
    for (const [pkg, comps] of byPkg) {
      // biome-ignore lint/style/noNonNullAssertion: comps derives from components, the same array used to build slugs
      parts.push(`### ${pkg}`, '', comps.map((c) => `snapds-${slugs.get(c.id)!}`).join(', '), '');
    }
    return parts.join('\n');
  }

  // folder + generic: full table with links to each detail file.
  parts.push(
    "- Open a component's detail file only when you actually use that component.",
    '',
    '## Components',
    '',
  );
  for (const [pkg, comps] of byPkg) {
    parts.push(`### ${pkg}`, '', '| Component | Skill |', '|-----------|-------|');
    for (const c of comps) {
      // biome-ignore lint/style/noNonNullAssertion: comps derives from components, the same array used to build slugs
      const slug = slugs.get(c.id)!;
      parts.push(`| ${splitComponentId(c.id).name} | ${routerLink(format, slug)} |`);
    }
    parts.push('');
  }
  return parts.join('\n');
}

/**
 * Builds skill artifacts for `components` under `format`. When `changedIds` is
 * provided, only the router plus detail files for those component ids are emitted
 * (incremental mode); otherwise every detail file is emitted (full mode).
 * Consolidated agents emit only their single always-rewritten catalog file;
 * `compact` drops the prop tables from that catalog.
 */
export function buildArtifacts(
  components: ComponentMeta[],
  format: SkillFormat,
  changedIds?: Set<string>,
  guidance?: ResolvedGuidance,
  compact = false,
): SkillArtifact[] {
  const agent = AGENTS[format];
  const slugs = resolveSlugs(components);
  // The router always reflects the full component set so routing stays correct.
  const artifacts: SkillArtifact[] = [
    {
      relativePath: agent.routerRelPath,
      contents: buildMainSkillMarkdown(components, format, slugs, guidance, compact),
    },
  ];
  if (!agent.componentRelPath) return artifacts;
  for (const meta of components) {
    if (changedIds && !changedIds.has(meta.id)) continue;
    // biome-ignore lint/style/noNonNullAssertion: meta is from components, the same array used to build slugs
    const slug = slugs.get(meta.id)!;
    artifacts.push({
      relativePath: agent.componentRelPath(slug),
      contents: buildComponentSkillMarkdown(meta, format, slug, guidance?.perComponent[meta.id]),
    });
  }
  return artifacts;
}
